name: crescensdo-music-service
services:
    postgresql:
        image: postgres:15.4-bullseye
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 10
    mongodb:
        image: mongo:8.0.4
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin123}
        volumes:
            - ./mongo-data:/data/db
        restart: always

    streaming:
        image: crescendo-streaming:1.0.0
        ports:
            - "8081:8081"
        environment:
            - ENV=CONTAINER
            - STREAMING_SERVICE_PORT=8081
            - MONGODB_HOST=mongodb-servidor
            - MONGODB_USER=${MONGO_USER:-admin}
            - MONGODB_PASSWORD=${MONGO_PASSWORD:-admin123}
            - MONGODB_PORT=27017
            - JWT_SECRET=${JWT_SECRET:-secret-key}
        depends_on:
            - mongodb
        restart: always

    crescendo-api:
        image: crescendo-api:1.0.0
        ports:
            - "8080:8080"
        environment:
            - ENV=CONTAINER
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - SQID_ALPHABET=${SQID_ALPHABET}
            - JWT_SECRET=${JWT_SECRET:-secret-key}
            - BASE_URL=${BASE_URL:-http://localhost:8081}
        depends_on:
            postgresql:
                condition: service_healthy 
